# Generated by Django 4.1.9 on 2023-06-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6)),
                ('nome', models.CharField(max_length=100)),
                ('moeda', models.CharField(max_length=10)),
                ('data_atualizacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sugestoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora_sugestao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6)),
                ('currency', models.CharField(max_length=10)),
                ('regularMarketPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regularMarketDayHigh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regularMarketDayLow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regularMarketTime', models.DateTimeField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.ativos')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_inferior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_superior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investimentos.ativos')),
            ],
        ),
        migrations.AddField(
            model_name='ativos',
            name='cotacoes',
            field=models.ManyToManyField(to='investimentos.cotacao'),
        ),
    ]
