# Generated by Django 4.1.9 on 2023-09-05 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6)),
                ('nome', models.CharField(max_length=100)),
                ('moeda', models.CharField(max_length=10)),
                ('data_atualizacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6)),
                ('currency', models.CharField(max_length=10)),
                ('regularMarketPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regularMarketDayHigh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regularMarketDayLow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regularMarketTime', models.DateTimeField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.ativos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6)),
                ('limite_inferior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_superior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.ativos')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ativos',
            name='cotacoes',
            field=models.ManyToManyField(to='investimentos.cotacao'),
        ),
        migrations.AddField(
            model_name='ativos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
